### ISSUE TITLE
Run on (ubuntu) Debian ?

### ISSUE THREAD

**Issue by pwnmactep** [splitbrain/pimenu#2]
Hi,

is it possible to run this on my Ubuntu System in a small Window ?

**Comment by splitbrain** [comment]
sure. just skip the full screen parameter

**Comment by pwnmactep** [comment]
Hi,
ty works now !

Could you explain how i can use the printed parameters to exec commands ?

like : 
Console Output is " kaddi bank"
and if that happent  i want to call the cmd "firefox www.MyBank.com" ? 

Hope you understand me xD
