### ISSUE TITLE
Writing specific functions for certain tiles in the "pimenu.sh.dist" file

### ISSUE THREAD

**Issue by MatthewDerenda** [splitbrain/pimenu#5]
I'm having a small issue with writing the code for running a certain function for a certain tile. I hope you understand. I am fairly new to programming especially with Shells. I have not been able to find any sort of advice on the internet so any help is appreciated. Currently every tile performs the same function and i would like to change that.

**Comment by splitbrain** [comment]
The shell file gets the pressed button name (and any previous menu levels) passed as separate parameters. You need to code the decision of what to do with that yourself.
